spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Tbl2425209089yyds
    url: jdbc:mysql://81.68.81.2:3306/mall?characterEncoding=utf-8&userSSL=false
  redis:
    host: 81.68.81.2
    port: 6379
    password: Tbl2425209089yyds
  rabbitmq:
    addresses: 81.68.81.2
    port: 5672
    username: guest
    password: Tbl2425209089yyds
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
security:
  header-token-key: token

server:
  port: 80